name: PR and Issue Activity Reminder via Slack

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Notifications
        uses: sonichigo/gh_slack_reminder@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_NAME: keploy
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
